### PR TITLE
API key admin panel

### LINKED ISSUE #1: Add admin panel so staff can view all assigned api keys, rotate them, and revoke them if necessary

### PR DESCRIPTION
**Pull request by jacobsandersen**
Closes #1.

Waiting for info before finishing.

### CODE REVIEW

**Comment by md-5** [comment]
Anything else required?

**Comment by jacobsandersen** [comment]
Still need to add pagination here, will get to it soon

**Comment by jacobsandersen** [comment]
demo: https://www.youtube.com/watch?v=d8tJoQT6Q5I

**Comment by jacobsandersen** [comment]
Implemented deletion by following how XF core does user deletion. Implemented key rotation by mimicking api key deletion, loosely followed user banning code but didn't need it to be as complex.

Should be fairly easy to follow. Let me know if any questions.

**Comment by jacobsandersen** [comment]
@md-5 reminder

**Comment by jacobsandersen** [comment]
@md-5 july reminder

**Pull request merged**
